platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 10 x64
  - npm install

build_script:
  - npm run dist

test: off

environment:
  GH_TOKEN:
    secure: FtK/1TBFTpILF8FUUXRkeWvWmxVYgWnIhby/J+IzIHYZxomJ4ERIfYY/Iid1ZOdJ
